/*
* generated by Xtext
*/
package dk.dtu.se2.animation;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AnimationLanguageStandaloneSetup extends AnimationLanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new AnimationLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

