/**
 * generated by Xtext
 */
package dk.dtu.se2.tutorials.tutorial6.animation.language.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
@SuppressWarnings("all")
public class AnimationLanguageOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
