/*
 * generated by Xtext
 */
package dk.dtu.se2.animation.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AnimationLanguageUiModule extends dk.dtu.se2.animation.ui.AbstractAnimationLanguageUiModule {
	public AnimationLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
