/*
 * generated by Xtext
 */
package dk.dtu.se2.tutorials.tutorial6.animationTest.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AnimationLanguageRuntimeModule extends dk.dtu.se2.tutorials.tutorial6.animationTest.language.AbstractAnimationLanguageRuntimeModule {

}
