/**
 * generated by Xtext
 */
package dk.dtu.se2.animation.serializer;

import dk.dtu.se2.animation.serializer.AbstractAnimationLanguageSyntacticSequencer;

@SuppressWarnings("all")
public class AnimationLanguageSyntacticSequencer extends AbstractAnimationLanguageSyntacticSequencer {
}
