/**
 * generated by Xtext
 */
package dk.dtu.se2.animation.serializer;

import dk.dtu.se2.animation.serializer.AbstractAnimationLanguageSemanticSequencer;

@SuppressWarnings("all")
public class AnimationLanguageSemanticSequencer extends AbstractAnimationLanguageSemanticSequencer {
}
