<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="appearance" nsURI="http://appearance/1.0" nsPrefix="appearance">
  <eClassifiers xsi:type="ecore:EClass" name="Appearance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aObjects" upperBound="-1"
        eType="#//AObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aObjects" upperBound="-1"
        eType="#//AObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id : Eint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" lowerBound="1"
        eType="#//3DObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name : EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="3DObject" eSuperTypes="#//AObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="file : File"/>
  </eClassifiers>
</ecore:EPackage>
