/*
 * generated by Xtext
 */
package dk.dtu.se2.tutorials.tutorial6.animationTest.language.ui.contentassist

import dk.dtu.se2.tutorials.tutorial6.animationTest.language.ui.contentassist.AbstractAnimationLanguageProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class AnimationLanguageProposalProvider extends AbstractAnimationLanguageProposalProvider {
}
