/*
* generated by Xtext
*/
package dk.dtu.se2.animation.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class AnimationLanguageGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class Animation_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Animation_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAnimationParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cSemicolonKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Action cSequenceAnimationsAction_1_1 = (Action)cGroup_1.eContents().get(1);
		private final Assignment cAnimationsAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cAnimationsAnimationParserRuleCall_1_2_0 = (RuleCall)cAnimationsAssignment_1_2.eContents().get(0);
		private final Group cGroup_1_3 = (Group)cGroup_1.eContents().get(3);
		private final Keyword cSemicolonKeyword_1_3_0 = (Keyword)cGroup_1_3.eContents().get(0);
		private final Assignment cAnimationsAssignment_1_3_1 = (Assignment)cGroup_1_3.eContents().get(1);
		private final RuleCall cAnimationsAnimationParserRuleCall_1_3_1_0 = (RuleCall)cAnimationsAssignment_1_3_1.eContents().get(0);
		
		//Animation_Impl returns Animation:
		//	Animation (";" {Sequence.animations+=current} animations+=Animation (";" animations+=Animation)*)?;
		public ParserRule getRule() { return rule; }

		//Animation (";" {Sequence.animations+=current} animations+=Animation (";" animations+=Animation)*)?
		public Group getGroup() { return cGroup; }

		//Animation
		public RuleCall getAnimationParserRuleCall_0() { return cAnimationParserRuleCall_0; }

		//(";" {Sequence.animations+=current} animations+=Animation (";" animations+=Animation)*)?
		public Group getGroup_1() { return cGroup_1; }

		//";"
		public Keyword getSemicolonKeyword_1_0() { return cSemicolonKeyword_1_0; }

		//{Sequence.animations+=current}
		public Action getSequenceAnimationsAction_1_1() { return cSequenceAnimationsAction_1_1; }

		//animations+=Animation
		public Assignment getAnimationsAssignment_1_2() { return cAnimationsAssignment_1_2; }

		//Animation
		public RuleCall getAnimationsAnimationParserRuleCall_1_2_0() { return cAnimationsAnimationParserRuleCall_1_2_0; }

		//(";" animations+=Animation)*
		public Group getGroup_1_3() { return cGroup_1_3; }

		//";"
		public Keyword getSemicolonKeyword_1_3_0() { return cSemicolonKeyword_1_3_0; }

		//animations+=Animation
		public Assignment getAnimationsAssignment_1_3_1() { return cAnimationsAssignment_1_3_1; }

		//Animation
		public RuleCall getAnimationsAnimationParserRuleCall_1_3_1_0() { return cAnimationsAnimationParserRuleCall_1_3_1_0; }
	}

	public class MoveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Move");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMoveAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMoveKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSpeedAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSpeedEDoubleParserRuleCall_3_0 = (RuleCall)cSpeedAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Move:
		//	{Move} "move" "(" speed=EDouble ")";
		public ParserRule getRule() { return rule; }

		//{Move} "move" "(" speed=EDouble ")"
		public Group getGroup() { return cGroup; }

		//{Move}
		public Action getMoveAction_0() { return cMoveAction_0; }

		//"move"
		public Keyword getMoveKeyword_1() { return cMoveKeyword_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }

		//speed=EDouble
		public Assignment getSpeedAssignment_3() { return cSpeedAssignment_3; }

		//EDouble
		public RuleCall getSpeedEDoubleParserRuleCall_3_0() { return cSpeedEDoubleParserRuleCall_3_0; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}

	public class AppearElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Appear");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAppearAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAppearKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cGeometryAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cGeometryEStringParserRuleCall_3_0 = (RuleCall)cGeometryAssignment_3.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cAppearanceAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cAppearanceEStringParserRuleCall_5_0 = (RuleCall)cAppearanceAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Appear:
		//	{Appear} "appear" "(" geometry=EString "," appearance=EString ")";
		public ParserRule getRule() { return rule; }

		//{Appear} "appear" "(" geometry=EString "," appearance=EString ")"
		public Group getGroup() { return cGroup; }

		//{Appear}
		public Action getAppearAction_0() { return cAppearAction_0; }

		//"appear"
		public Keyword getAppearKeyword_1() { return cAppearKeyword_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }

		//geometry=EString
		public Assignment getGeometryAssignment_3() { return cGeometryAssignment_3; }

		//EString
		public RuleCall getGeometryEStringParserRuleCall_3_0() { return cGeometryEStringParserRuleCall_3_0; }

		//","
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }

		//appearance=EString
		public Assignment getAppearanceAssignment_5() { return cAppearanceAssignment_5; }

		//EString
		public RuleCall getAppearanceEStringParserRuleCall_5_0() { return cAppearanceEStringParserRuleCall_5_0; }

		//")"
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
	}

	public class AnimationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Animation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMoveParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAppearParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Animation:
		//	Move | Appear;
		public ParserRule getRule() { return rule; }

		//Move | Appear
		public Alternatives getAlternatives() { return cAlternatives; }

		//Move
		public RuleCall getMoveParserRuleCall_0() { return cMoveParserRuleCall_0; }

		//Appear
		public RuleCall getAppearParserRuleCall_1() { return cAppearParserRuleCall_1; }
	}

	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//EDouble returns ecore::EDouble:
		//	"-"? INT? "." INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT? "." INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }

		//"."
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }

		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	
	
	private Animation_ImplElements pAnimation_Impl;
	private MoveElements pMove;
	private AppearElements pAppear;
	private AnimationElements pAnimation;
	private EDoubleElements pEDouble;
	private EIntElements pEInt;
	private EStringElements pEString;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public AnimationLanguageGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("dk.dtu.se2.animation.AnimationLanguage".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Animation_Impl returns Animation:
	//	Animation (";" {Sequence.animations+=current} animations+=Animation (";" animations+=Animation)*)?;
	public Animation_ImplElements getAnimation_ImplAccess() {
		return (pAnimation_Impl != null) ? pAnimation_Impl : (pAnimation_Impl = new Animation_ImplElements());
	}
	
	public ParserRule getAnimation_ImplRule() {
		return getAnimation_ImplAccess().getRule();
	}

	//Move:
	//	{Move} "move" "(" speed=EDouble ")";
	public MoveElements getMoveAccess() {
		return (pMove != null) ? pMove : (pMove = new MoveElements());
	}
	
	public ParserRule getMoveRule() {
		return getMoveAccess().getRule();
	}

	//Appear:
	//	{Appear} "appear" "(" geometry=EString "," appearance=EString ")";
	public AppearElements getAppearAccess() {
		return (pAppear != null) ? pAppear : (pAppear = new AppearElements());
	}
	
	public ParserRule getAppearRule() {
		return getAppearAccess().getRule();
	}

	//Animation:
	//	Move | Appear;
	public AnimationElements getAnimationAccess() {
		return (pAnimation != null) ? pAnimation : (pAnimation = new AnimationElements());
	}
	
	public ParserRule getAnimationRule() {
		return getAnimationAccess().getRule();
	}

	//EDouble returns ecore::EDouble:
	//	"-"? INT? "." INT;
	public EDoubleElements getEDoubleAccess() {
		return (pEDouble != null) ? pEDouble : (pEDouble = new EDoubleElements());
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return (pEInt != null) ? pEInt : (pEInt = new EIntElements());
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
