/**
 * generated by Xtext
 */
package dk.dtu.se2.tutorials.tutorial6.animationTest.language.serializer;

import dk.dtu.se2.tutorials.tutorial6.animationTest.language.serializer.AbstractAnimationLanguageSemanticSequencer;

@SuppressWarnings("all")
public class AnimationLanguageSemanticSequencer extends AbstractAnimationLanguageSemanticSequencer {
}
