/**
 * generated by Xtext
 */
package dk.dtu.se2.tutorials.tutorial6.animationTest.language.scoping;

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it
 */
@SuppressWarnings("all")
public class AnimationLanguageScopeProvider extends AbstractDeclarativeScopeProvider {
}
