/*
* generated by Xtext
*/
package dk.dtu.se2.animation;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AnimationLanguageUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return dk.dtu.se2.animation.ui.internal.AnimationLanguageActivator.getInstance().getInjector("dk.dtu.se2.animation.AnimationLanguage");
	}
	
}
