/*
 * generated by Xtext
 */
package dk.dtu.se2.tutorials.tutorial6.animationTest.language.serializer

class AnimationLanguageSyntacticSequencer extends AbstractAnimationLanguageSyntacticSequencer {
}
