/**
 * generated by Xtext
 */
package dk.dtu.se2.animation.validation;

import dk.dtu.se2.animation.validation.AbstractAnimationLanguageValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class AnimationLanguageValidator extends AbstractAnimationLanguageValidator {
}
