/*
 * generated by Xtext
 */
package dk.dtu.se2.tutorials.tutorial6.animationTest.language.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import dk.dtu.se2.tutorials.tutorial6.animationTest.language.ui.internal.AnimationLanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AnimationLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AnimationLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AnimationLanguageActivator.getInstance().getInjector(AnimationLanguageActivator.DK_DTU_SE2_TUTORIALS_TUTORIAL6_ANIMATIONTEST_LANGUAGE_ANIMATIONLANGUAGE);
	}
	
}
