/**
 * generated by Xtext
 */
package dk.dtu.se2.tutorials.tutorial6.animation.language.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class AnimationLanguageQuickfixProvider extends DefaultQuickfixProvider {
}
