/**
 * generated by Xtext
 */
package dk.dtu.se2.animation.ui.contentassist;

import dk.dtu.se2.animation.ui.contentassist.AbstractAnimationLanguageProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class AnimationLanguageProposalProvider extends AbstractAnimationLanguageProposalProvider {
}
