/**
 * generated by Xtext
 */
package dk.dtu.se2.tutorials.tutorial6.animation.language.serializer;

import dk.dtu.se2.tutorials.tutorial6.animation.language.serializer.AbstractAnimationLanguageSyntacticSequencer;

@SuppressWarnings("all")
public class AnimationLanguageSyntacticSequencer extends AbstractAnimationLanguageSyntacticSequencer {
}
